#!/usr/bin/env bash

source "${HALCYON_TOP_DIR}/src.sh"


slug_post_build_hook () {
	expect_vars HALCYON_DIR

	local tag source_dir slug_dir
	expect_args tag source_dir slug_dir -- "$@"

	copy_dir_into "${HALCYON_DIR}/app/snaplets" "${slug_dir}/app/snaplets" || return 1
	copy_dir_into "${HALCYON_DIR}/app/static" "${slug_dir}/app/static" || return 1
}


slug_post_build_hook "$@"
